---

- name: Generate an OpenSSH keypair on ssh_host
  community.crypto.openssh_keypair:
    path: "{{ ssh_path }}"
    type: "{{ ssh_keytype }}"
    comment: "{{ ssh_comment }}"
    regenerate: 'never'
  register: _result_keypair
  delegate_to: "{{ ssh_host }}"

- name: Set facts from keypair
  ansible.builtin.set_fact:
    authorized_key: "{{ _result_keypair.public_key + ' ' + _result_keypair.comment }}"
    keypair_pubkey: "{{ _result_keypair.public_key }}"
    keypair_comment: "{{ _result_keypair.comment }}"
  delegate_to: "{{ ssh_host }}"
  delegate_facts: true
