---
# tasks file for user.example
- name: Ensure the httpd package is installed
  ansible.builtin.dnf:
    name: httpd
    state: latest
- name: Service is enabled and started
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
- name: Open the ports
  ansible.posix.firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled
- name: Serve the content
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
